apiVersion: apps/v
kind: Deployment
metadata:
  name: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: mguay/ordering-app_billing
          env:
            - name: RABBIT_MQ_BILLING_QUEUE
              value: billing
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth